version: "3.5"

services:
  traefik:
    image: traefik:1.7-alpine@sha256:2d3763c9c89ce9081a0df872ea573a4f60277f1b8e4f6efda0ef600fd1ecf3bc
    read_only: yes
    command: --api --docker --docker.exposedbydefault=false
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./traefik.toml
        target: /traefik.toml
      - type: bind
        source: ./acme.json
        target: /acme.json
    networks:
      - traefik
  anschluss:
    image: quay.io/westnetz/anschluss:edge
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HOSTNAME}"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
    environment:
      - DJANGO_ADMINS
      - DJANGO_ALLOWED_HOSTS=${HOSTNAME}
      - DJANGO_DEFAULT_FROM_EMAIL
      - DJANGO_EMAIL_HOST
      - DJANGO_EMAIL_HOST_PASSWORD
      - DJANGO_EMAIL_HOST_USER
      - DJANGO_SECRET_KEY

networks:
  traefik:
    external:
      name: traefik
