version: "3.5"

services:
  traefik:
    image: traefik:1.7-alpine@sha256:cf30141936f73599e1a46355592d08c88d74bd291f05104fe11a8bcce447c044
    read_only: yes
    command: --api --docker --docker.exposedbydefault=false
    ports:
      - 80:80
      - 443:443
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: ./traefik.toml
        target: /traefik.toml
      - type: bind
        source: ./acme.json
        target: /acme.json
    networks:
      - traefik
  anschluss:
    image: quay.io/westnetz/anschluss:edge@sha256:6f4b8c78e42f9fcc6678e43add71496474bcfdde7c8133ae698122f707af8ad3
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${HOSTNAME}"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
    environment:
      - DJANGO_ADMINS
      - DJANGO_ALLOWED_HOSTS=${HOSTNAME}
      - DJANGO_DEFAULT_FROM_EMAIL
      - DJANGO_EMAIL_HOST
      - DJANGO_EMAIL_HOST_PASSWORD
      - DJANGO_EMAIL_HOST_USER
      - DJANGO_SECRET_KEY

networks:
  traefik:
    external:
      name: traefik
